name: ed_sample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.3+1
  get_it: ^7.6.7
  injectable: ^2.3.1
  json_annotation: ^4.9.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.6
  built_value: ^8.1.4
  meta: ^1.9.1
  another_flushbar: ^1.12.30
  shimmer: ^3.0.0
  rename: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  animations: ^2.0.8
  firebase_core: ^2.24.2
  flutter_launcher_icons: ^0.13.1
  sizer: ^2.0.15
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.9
  built_value_generator: ^8.9.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.2
  json_serializable: ^6.8.0

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#ffd000" # Yellow background
  image_path: "assets/images/icon.png"

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

flutter_lints: ^2.0.0